[package]
name = "stdsimd-nvptx-kernels"
version = "0.0.0"
edition = "2018"
authors = [
    "Peter Jin <peterhaijin@gmail.com>",
]

[workspace]
members = []

[dependencies]
coresimd = { path = "../coresimd" }

[features]
default = []
